//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Ordering_Setting
    {
        public int Customer_Setting_No { get; set; }
        public Nullable<int> No_Item { get; set; }
        public Nullable<int> Qnty_Item { get; set; }
        public Nullable<int> No_CancelHRS { get; set; }
    }
}
