//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefualtImage
    {
        public string DefProdImageCode { get; set; }
        public byte[] DefProdImage { get; set; }
        public string DefImageCategory { get; set; }
    }
}
