//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryEntryList
    {
        public int InventryListCode { get; set; }
        public string EntryCode { get; set; }
        public string ProductCode { get; set; }
        public string ProdName { get; set; }
        public Nullable<int> OnlineStock { get; set; }
        public Nullable<int> StoreStock { get; set; }
        public string PurchasePrice { get; set; }
        public Nullable<int> TotalStock { get; set; }
        public Nullable<decimal> StockTotalAmnt { get; set; }
        public Nullable<short> DaysToBeDlvd { get; set; }
    
        public virtual InventoryEntry InventoryEntry { get; set; }
    }
}
