//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public string ProcessID { get; set; }
        public string value1 { get; set; }
        public string Email { get; set; }
        public string DateTime { get; set; }
    
        public virtual LogProcess LogProcess { get; set; }
        public virtual User User { get; set; }
    }
}
