//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int OrderListID { get; set; }
        public Nullable<int> OrderCode { get; set; }
        public string OrderProdCode { get; set; }
        public string OrderProdName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SubTotalPrice { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
    }
}
