//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductCode { get; set; }
        public string ProdName { get; set; }
        public string ProductBrand { get; set; }
        public string Description { get; set; }
        public string ProdCategory { get; set; }
        public Nullable<decimal> ProdPrice { get; set; }
        public Nullable<decimal> ProdSellingPrice { get; set; }
        public Nullable<int> OnlineShopStock { get; set; }
        public Nullable<int> StoreStock { get; set; }
        public string ProdUnitWght { get; set; }
        public string ProdSuppID { get; set; }
        public string ProdStatus { get; set; }
        public Nullable<int> ProdReOrderLvl { get; set; }
        public Nullable<int> ReserveStock { get; set; }
        public Nullable<double> ProdAvgUsage { get; set; }
        public Nullable<decimal> TotalAmnt { get; set; }
        public Nullable<int> TotalStock { get; set; }
        public string ProdLastDateDvrd { get; set; }
        public string ProdCreateDate { get; set; }
        public Nullable<int> Total_Lead_inDays { get; set; }
        public byte[] ProductImage { get; set; }
        public Nullable<short> No_Delivery { get; set; }
        public Nullable<int> Sold_Qnty { get; set; }
        public Nullable<double> ProdAvgUsage_Online { get; set; }
        public Nullable<int> Sold_Qnty_Online { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
