//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTransaction
    {
        public int Sale_Transac_Code { get; set; }
        public string SalesCode { get; set; }
        public string TransactionCode { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
