//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightShope_B2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Logs = new HashSet<Log>();
            this.Transactions = new HashSet<Transaction>();
            this.UserOrders = new HashSet<UserOrder>();
        }
    
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Level { get; set; }
        public string Gender { get; set; }
        public string BirthDate { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string City_Province { get; set; }
        public byte[] UserPhoto { get; set; }
        public string Active { get; set; }
        public string Password { get; set; }
        public string CreateDate { get; set; }
        public Nullable<long> UserPoints { get; set; }
        public Nullable<int> Success_Order { get; set; }
        public Nullable<byte> Unread_Notification { get; set; }
        public Nullable<byte> Unread_Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrder> UserOrders { get; set; }
    }
}
